language: node_js

node_js:
  - "7.2"

sudo: false

branches:
  only:
    - /.*/

before_install:
  - npm i -g npm@4

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  # run linter
  - npm run lint

  # run test suite
  - node node_modules/jest/bin/jest.js
